let firstName = "Danny";
let age = 25;
let isCool = true;
let isHot = false;
let length = 1.75;
let notDefined = undefined;
let nullValue = null;
let animal = "Owlbears";
let dndClass = "fighter"
let race = "half-elf";
let map = "farendell";
let trueTemperature = isCool || isHot;
let falseTemprature = isCool || isHot;
let oppositeTemperature = !isCool;
let party = ["Danny", "Eliza", "Analyn", "Joe"];
let charisma = [10, 12, 11, 15];
let addition = 1 + 1;
addition += 1;
let substraction = 10 - 2;
substraction -= 1;
let multiplication = 10 * 10;
multiplication *= 10;
let division = 10 / 2;
division /= 1;
let modulo = 10 % 4;
modulo %= 3;
let exponentiation = 4 ** 3;
exponentiation **= 5;
let firstDigit = danny[1];
let nameLength = firstName.length;
let nameAge = '(' + firstName + ', ' + age + ')';
let uppercaseName = firstName.toUpperCase();
let lowercaseName = firstName.toLowerCase();
let player2Name = "Eliza";
let player2Age = 25;
let isPlayer2Alive = true;
let isPlayer1Name = firstName;
let isPlayer1Alive = true;
let isPartyAlive = isPlayer1Alive && isPlayer2Alive;
let player1Object = { name: "Danny", class: "fighter", age: 25 }
let player2Object = { name: "Eliza", class: "druid", age: 25 }
let greet = function() { console.log("Hello World"); };
let summation = function(a, b) { return a + b; }; 
let Rectangle = class { constructor(length, width) {this.length = length; this.width = width; } };
let fetchData = fetch();
let helloWorld = () => { console.log("Hello World") };
let pie = 3.14;
let truth = true;
let nothing = null;
let fifty = 50;
const first = 1;
const numStr = "1";
const isFalse = !true;
const isTrue = !false;
const lastName = "chandler";
const payment = 40.12;
const car = "honda";
const make = "civic";
const cars = ["honda", "toyota", "kia"];
const carMake = car + " " + make;
const subtract = (a, b) => { return a - b };
const greaterThan = 10 > 5;
const greaterThanEquals = 10 >= 10;
const lessThan = 5 < 10;
const lessThanEquals = 5 <= 5;
const strictEquals = 5 === "5";
const notStrictEquals = 5 !== "5"; // yields true if they are not equal
const equals = 5 == "5";
const notEquals = 5 != "5";
const letters = ['a', 'b', 'c'];
const numbers = [1, 2, 3, 4, 5];
const longPhrase = "creating 100 variables is insane";
const four = 2 + 2;
const ten = 20 / 2;
const oneHundred = 10 * 10;
const nullable = null;
const notThere = undefined;
const doesNotExist = null;
const truthy = 1;
const falsy = 0;
const oneMillion = 1000000;
const oneHundredMillion = "One hundred million";
const currency = ['USD', 'EUR'];
const president = "Obama";
const continents = { "North America": ["United States of America", "Mexico", "Canada"]};
const amountOwed = 100.45;
const visitors = { name:"Verena", age: 45, code: "1o23iup5iou"};
const villain = { "Ret": [34, 34, 12, 12], "Trel": [12, 14, 15, 96]};
const eighty8 = 88;
const almost = "there";
const ticketNumber = 12354859;
const isWinter = true;
const isSummer = false;
const isSpring = !isWinter && isSummer;
const nine = 9;
const eight = 9 - 1;
const sixty4 = 8 ** 2;
const twoMore = sixty4 + 2;
const oneMore = twoMore + 1;
const isDone = true;



